# Generated by Django 5.1.7 on 2025-04-02 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
